--- # webserver setup
- hosts: webserver
  user: 444
  sudo: yes
  tasks:
  - name: installing httpd package
    yum: name=httpd state=installed
  - name: service httpd start
    service: name=httpd state=started 
